const projects = [
    {
        title: "Choose Your Own Adventure",
        color: "school",
        src: "images/story-game.png",
        alt: "An image showcasing a python project, showing both a portion of the code and it being run.",
        type: "File Name: storygame.py",
        tags: ["Class Project", "Python"],
        description: [
            "Purpose: To learn how to utlize nested if's in python. This assignment was assigned in CSE110.",
            "I decided I wanted to seperate the story chunks from the code itself, and as such gained an early introduction", 
            "to python functions to be able to call the predifined chunks of code. This also enabled me to loop one branch",
            "of the story to another as I decided was necessary.",
        ]
    },
    {
        title: "Sleepy Chef Search",
        color: "personal",
        src: "images/sleep-chef-search.png",
        alt: "An image showcasing a python project, showing both a portion of the code and the csv file it is referencing",
        type: "File Name: sleepy-chef-search.py",
        tags: ["Personal Project", "Class Project", "Python"],
        description: [
            "Purpose: To combine all of what we had learned in CSE111 and make our own personal program.",
            "I decided that I wanted to make a local meal aid for people who have difficulty making decisions.",
            "This program uses a file that it reads and writes to. It has multiple functions, such as displaying",
            "all the recipes it has stored with minmal information to prevent user overwhelm, search based off of ",
            "certain criteria and returning tha matching results,",
            "and a step by step process for adding or removing recipes as needed. It is to this day one of my ",
            "proudest projects, as I came up with the project myself, and with some trial and error, got it working.",
        ]
    },
    {
        title: "This Spark",
        color: "personal",
        src:"images/spark-fixed.jpg",
        alt:"A picture of a masked and hooded woman, covered in inky tentacles, holding a magical and flaming sphere.",
        type: "Art Type: Ink on Paper",
        tags: ["Personal Project", "Physical Art"],
        description: [
            "This is a personal project made to combat the idea that human creativity is being overwritten by ",
            "recent technological advancement. It took me over 10 hours to complete and is conveys the overall ",
            "of seizing our creativity despite the forces that want us to give in to the bleak.",
        ],
    },
    {
        title: "",
        color: "personal",
        src:"",
        alt:"",
        type:"",
        tags: [],
        description: [],
    },
    {
        title: "ZMAForge Home Ver.1",
        color: "class",
        src: "images/homev1.png",
        alt: "An image of a redimentary and static home page.",
        type: "File Names: index.html, styles/style.css",
        tags: ["Class Project", "HTML", "CSS"],
        description: [
            "Purpose: Create our own wireframe, and build a site that meets that wireframe, while reinforcing ",
            "familiarity with HTML and CSS. The assignment we were given was to make a page to advertise ourselves.",
            "This project became the basis for this page, and was referenced when working on the style guide. It includes ",
            "Links to other pages made during the introductory WebDev class, as well as a reflection on a Web Dev Professional",
            "Simulation that we completed."
        ],
    },
    {
        title: "Snortleblast Character Card",
        color: "class",
        src: "images/snortleJS.png",
        alt: "an image containing the JavaScript for the snortleblast card, focused primarily on a function that updates the page after a change is made.",
        type: "File Names: index.html, scripts.js, and styles.css",
        tags: ["Class Project", "JavaScript", "HTML", "CSS"],
        description: [
            "Purpose: To introduce the class to utilizing objects for complex elements, and editing dynamically portions of ",
            "those elements, as well as visually displaying those changes. This assigment had predifined HTML and CSS leading to ",
            "the choice to display the code instead. I was excited to learn this as it has aligned with a long term personal project ",
            "that I have been wanting to create, and objects seem like they will be essential for that.",
        ],
    },
    {
        title: "Dads Place Janitor",
        color: "skills",
        src: "images/dads-place.jpg",
        alt: "An image showing a driveway through the woods, the sun shining through the leaves.",
        type: "Job Position: Sanitation Expert",
        tags: ["Job", "Inventory Management", "Adaptive Work Processes", "Janitorial"],
        description: [
            "Job Overview: I was tasked with keeping an assisted living residence clean for 5 residents, which then ",
            "grew to 7 during my work there. I was in charge in memorizing the different cleaning process for each of ",
            "the residents, as well as specific cleaning processes for different materials. I was asked to work for exactly ",
            "4 hours in a single rush, so I had to adapt cleaning time to be meticulous and perfect in order to help protect ",
            "the residents as well as meet this tight time frame. Furthermore, the route and methods used had to change based off ",
            "of where each resident currently was, as well as around meal times, and guest visits. It was a physically ",
            "demanding but spirtually fulfilling position.",
        ]
    },
    {
        title: "National Honors Society",
        color: "skills",
        src: "",
        alt:"",
        type: "Position: Historian",
        tags: ["Extracurricular", "Leadership Position", "Planning and Documentation"],
        description: [
            "A position I held for 2 years in the John Adams Academy-Lincoln NHS Charter. My Job was primarily recording ",
            "the events of each of our meetings, and visually compile them into the charters history books, scrapbook style. ",
            "Beyond that, I was also in charge of planning and preparring meetings and service oppurtunties, as well as helping ",
            "to facilitate meetings, and ensure that each member submitted forms on time. It taught me a lot about the ",
            "difficulties of working with others, even when they are driven towards the same end goal.",
        ],
    },
    {
        title: "John Adams Academy-Lincoln Yearbook Team",
        color: "skills",
        src:"",
        alt:"",
        type: "Position Held: Design Editor",
        tags: ["Extracurricular", "Leadership Position", "Training and Aiding"],
        description: [
            "I worked on the yearbook team at JAA-L for 3 years. It is often very demanding work, requireing skipping ",
            "classes and activities in order to our work, as well as showing up to nearly every school event. This is ",
            "not including the high learning curve of learning about photography and the tricky website and design practices ",
            "we had to keep in mind. Deciding these challenges to be worth conquering, I was quickly raised to a position of ",
            "authority and given many tasks, such as designing the basis for almost every page of the book, being personally ",
            "responsible for at least 40 pages myself, and helping as both teacher and advisor for every other member of the ",
            "crew. The main difficulty came in the change of management during our last year, where we lost an Advisor with a ",
            "penchent for the work, and forced to make due with the only replacement that could be found.",
        ],
    },
]